# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 367842777ac1b4deeda592f39f62d234355f9d98be02d8316ec809f698177116f593540d16744688c929cca181835b3d103f41ad507a69d45f6583fc9e558bb2

test:
  secret_key_base: 27fd0e280003f7571fd614d82a1c1f629a3d4f063f6c7dd50a9046b6457e00ae23acbc69f2be64b9047f50a2ea827c62b902410c085295e1176f8f2140b52864

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
